# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    groups:
      dotnet:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    groups:
      github-actions:
        patterns:
          - "*"
