//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneInfoCompilerW.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WinmapFilePath {
            get {
                return ((string)(this["WinmapFilePath"]));
            }
            set {
                this["WinmapFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ResX")]
        public global::NodaTime.ZoneInfoCompiler.ResourceOutputType WinmapResourceOutputType {
            get {
                return ((global::NodaTime.ZoneInfoCompiler.ResourceOutputType)(this["WinmapResourceOutputType"]));
            }
            set {
                this["WinmapResourceOutputType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TzdbSourceDirectoryName {
            get {
                return ((string)(this["TzdbSourceDirectoryName"]));
            }
            set {
                this["TzdbSourceDirectoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TzdbTargetFileName {
            get {
                return ((string)(this["TzdbTargetFileName"]));
            }
            set {
                this["TzdbTargetFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ResX")]
        public global::NodaTime.ZoneInfoCompiler.ResourceOutputType TzdbResourceOutputType {
            get {
                return ((global::NodaTime.ZoneInfoCompiler.ResourceOutputType)(this["TzdbResourceOutputType"]));
            }
            set {
                this["TzdbResourceOutputType"] = value;
            }
        }
    }
}
